channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=24.0
- pip:
  - mlflow==2.12.1
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.24.4
  - packaging==23.1
  - pandas==2.0.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
  - xgboost==2.0.3
name: mlflow-env
